#!/usr/bin/env bash
# Client configuration

host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	sendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
